server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/victorysq
#    url: jdbc:mysql://localhost:3307/basics?allowPublicKeyRetrieval=true
    username: root
    password: ghost
  jpa:
    hibernate:
      ddl-auto: update
    database-platform : org.hibernate.dialect.MySQLDialect

  application :
    name : authentication-service

eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/