server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://database/victorysq
#    url: jdbc:mysql://localhost:3307/basics?allowPublicKeyRetrieval=true
    username: todorokishoto
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform : org.hibernate.dialect.MySQLDialect

  application :
    name : authentication-service

eureka :
  client :
    serviceUrl :
      defaultZone : http://eureka:8761/eureka

  