# Elasticsearch Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elk
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
            - name: ELASTIC_PASSWORD
              value: changeme
            - name: discovery.type
              value: single-node
          volumeMounts:
            - name: elasticsearch-data
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch-data
          emptyDir: {}

---
# Elasticsearch Service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elk
spec:
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
    - protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: elasticsearch

# Logstash ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: elk
data:
  logstash.conf: |
    input {
        tcp {
            port => 4560
            codec => json
        }
    }
    output {
        elasticsearch {
            hosts => ["http://elasticsearch:9200"]
            index => "victory-gateway-%{+YYYY.MM.dd}"
        }
        stdout {
            codec => rubydebug
        }
    }

---
# Logstash Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:7.15.2
          ports:
            - containerPort: 4560
            - containerPort: 5044
            - containerPort: 5000
            - containerPort: 9600
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx256m -Xms256m"
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config

---
# Logstash Service
apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: elk
spec:
  ports:
    - protocol: TCP
      port: 4560
      targetPort: 4560
    - protocol: TCP
      port: 5044
      targetPort: 5044
    - protocol: TCP
      port: 5000
      targetPort: 5000
    - protocol: TCP
      port: 9600
      targetPort: 9600
  selector:
    app: logstash


---
# Kibana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.15.2
          ports:
            - containerPort: 5601

---
# Kibana Service
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: elk
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    app: kibana

                  
