apiVersion: apps/v1
kind: Deployment
metadata:
    name: eureka-deployment
    labels:
        app: eureka

spec:
    replicas: 1
    selector:
        matchLabels:
            app: eureka
    template:
        metadata:
            labels:
                app: eureka
        spec:
            containers:
            -   name: eureka
                image: todorokishotoua15/eureka-server
                ports:
                -   containerPort: 8761

---
apiVersion: v1
kind: Service
metadata:
    name: eureka

spec:
    selector:
        app: eureka
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8761
          targetPort: 8761
          nodePort: 30000
