apiVersion: apps/v1
kind: Deployment
metadata:
    name: microservices
    labels:
        app: microservices

spec:
    replicas: 1
    selector:
        matchLabels:
            app: microservices
    template:
        metadata:
            labels:
                app: microservices
        spec:
            containers:
            -   name: auth
                image: todorokishotoua15/auth
                ports:
                -   containerPort: 9001
            -   name: game-service
                image: todorokishotoua15/game-service
                ports:
                -   containerPort: 9005
            -   name: gateway
                image: todorokishotoua15/gateway

                ports:
                -   containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
    name: microservices
    labels:
      app: microservices

spec:
    selector:
        app: microservices
    type: LoadBalancer
    ports:
        - name: auth
          protocol: TCP
          port: 9001
          targetPort: 9001
          nodePort: 30005
        - name: game-service
          protocol: TCP
          port: 9005
          targetPort: 9005
          nodePort: 30006
        - name: gateway
          protocol: TCP
          port: 9003
          targetPort: 9003
          nodePort: 30007
