services:
  database:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: victorysq
      MYSQL_USER: todorokishoto
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - springmysql  
  
  
  eureka:
    image: eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - springmysql

  auth:
    image: auth
    container_name: auth
    depends_on:
      - database
    # environment:
    #   MYSQL_URL: jdbc:mysql://mysql-container:3306/inventory?autoReconnect=true&useSSL=false
    #   MYSQL_USERNAME: root
    #   MYSQL_PASSWORD: root
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    networks:
      - springmysql

networks:
  springmysql:
    name: springmysql