server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/victorysq
    username: root
    password: ghost
  jpa:
    hibernate:
      ddl-auto: update
    database-platform : org.hibernate.dialect.MySQLDialect

  application :
    name : game-service

eureka :
  client :
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/