server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://database/victorysq
    username: todorokishoto
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform : org.hibernate.dialect.MySQLDialect

  application :
    name : game-service

eureka :
  client :
    serviceUrl :
      defaultZone : http://eureka:8761/eureka